### ISSUE TITLE
Test Reporter Request

### ISSUE THREAD

**Issue by sheffierobinson** [WordPress/phpunit-test-runner#100]
Please add user wpclover as a test reporter. Thank you.

**Comment by getsource** [comment]
Hi Sheffie,

Thanks for the request!
I took a look at the WordPress profile, and it doesn't currently make it very clear which host it is for.

Could you please update the profile (Name, Logo/Gravatar, URL) so that visitors to the hosting test results page (https://make.wordpress.org/hosting/test-results/) can tell who is contributing results?

Thanks so much!

**Comment by sheffierobinson** [comment]
Hi there,

I updated the profile. The gravatar is taking a second though but everything is there. Let me know what else you need from me. Thank you.

**Comment by getsource** [comment]
Looks good -- thanks so much!

I added the test reporter account, and you should receive an invitation to the email address on the `wpclover` WordPress.org profile.

Please let me know if you have any questions!
