### ISSUE TITLE
Support both ImageMagick and GraphicsMagic

### ISSUE THREAD

**Issue by ottok** [WordPress/phpunit-test-runner#65]
GraphicsMagic is an improved fork of ImageMagic. WordPress works with both and this tester should support both of them. Currently it does not, because it runs `convert` and `convert --version` and not at all `gm convert` or `gm version`.

**Comment by ottok** [comment]
I did this ImageMagick wrapper as a work-around for now. Place it in your global path (e.g. `/usr/local/bin/` and make executable to work.

```
#!/bin/bash
if [[ $@ == '--version' ]]
then
  gm version
else
  gm convert $@
fi
```

**Comment by danielbachhuber** [comment]
> WordPress works with both and this tester should support both of them.

Off the top of your head, do you know whether WordPress Travis CI tests run against both GM and IM?

**Comment by ottok** [comment]
Nothing special is defined in https://github.com/WordPress/wordpress-develop/blob/master/.travis.yml, so I assume Travis has available the default Ubuntu 14.04 ImageMagick (pulled in by e.g. cups-filters package). I have not tested though.

**Comment by getsource** [comment]
Sorry I'm just seeing this now, but thought I'd provide some context anyway, albeit late.

The WordPress Travis CI tests do not run against Imagick (they are currently skipped), and WordPress does not natively support the Gmagick extension.

In theory, if a user has the Imagick PHP extension installed with Graphicsmagick binaries backing it, this should work, but I haven't personally done any testing of this.

I don't believe the WordPress phpunit tests directly call `convert` -- are you suggesting a workaround for the above (Imagick+Graphicsmagick binaries) setup?

**Comment by mrxkon** [comment]
Even though the unit tests aren't calling a `convert` the test-runner does for logging & reporting purposes.

Ref:
https://github.com/WordPress/phpunit-test-runner/blob/master/functions.php#L214
https://github.com/WordPress/phpunit-test-runner/blob/master/prepare.php#L80

I'll give it a try to setup a local with GraphicsMagic instead and see what could be changed here in order to support both returns from shell_exec.

**Comment by ottok** [comment]
Any updates here?

I am still seeing:
```
~/phpunit-test-runner$ php test.php
Environment variables pass checks.
cd '/tmp/wp-test-runner'; php phpunit.phar
sh: 1: convert: not found
sh: 1: convert: not found
PHP version: 7.4.10 (/usr/bin/php7.4)
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
...
```

**Comment by getsource** [comment]
Thanks for bringing this up!

Definitely think it'd be a good idea to change this so that if the executables / non-required environment information is missing, the test results still get submitted.

**Comment by mrxkon** [comment]
Hey lovely folks, sorry for being so late here but didn't had time at all unfortunately. I hope everyone is fine!

Getting back to this, bear with me so we can all be on the same page after I've run some tests etc as well as I've setup GraphicsMagick as well (but most likely missing some parts also since I've never used it 😁 ). There are a couple of things to consider overall to see what would be the best solution here.

---

First of all let's decouple the "Imagick" module vs the actual ImageMagick package ( which includes `convert` also ).

WordPress has the `WP_Image_Editor_Imagick` & `WP_Image_Editor_GD` as media handling editors. WP_Image_Editor_Imagick is going to be loaded if you simply have `Imagick` module, there's no need to have the actual ImageMagick package.

I'm throwing this here as the systems that we're using also don't have `convert` since the actual ImageMagick package isn't installed so I am still getting the `sh: 1: convert: not found` as well since it's missing, but that's minor imho as the module actually exists.

Site Health will also check against `Imagick` class or `gd_info()` similarly to showcase what is used on the site.

With the above being said when I loaded GraphicsMagick & Gmagick respectfully, WP always reverted to using GD instead since there's no mention of Gmagick anywhere in core (as far as I could find).

Example this is the Site Health info shown with GraphicsMagick enabled instead.

PHP Info of module being properly loaded:
![image](https://user-images.githubusercontent.com/22611066/104319331-61366500-54e9-11eb-99cf-d91ae46de70a.png)

Site Health reporting for Media Handling:
![image](https://user-images.githubusercontent.com/22611066/104319537-ad81a500-54e9-11eb-94f2-c12ea50f575e.png)

The above information are just added to see if we should "in general" show any information related to Gmagick since it's not used by core itself.

---

Now to the actual test runner:

The runner is passing 2 informational values in the reported array, 1 is the `imagick` module version via `phpversion( 'imagick' )` ( https://github.com/WordPress/phpunit-test-runner/blob/master/functions.php#L211 ) and then it also passes the `imagemagick` ImageMagick package version under `system_utils` by getting the `convert` version ( https://github.com/WordPress/phpunit-test-runner/blob/master/functions.php#L217 ).

I'm not even sure at this point if we actually need the `convert` and the package being reported at all since only having the `imagick` module is what's actually needed to run `WP_Image_Editor_Imagick`.

---

In my opinion to get the best of both worlds here if Gmagick needs to be reported and avoid these errors we can remove the `convert` (no need to read the imagemagick package) and simply add the `gmagick`  as a php_module check instead.

This would return this as an example:
```
 ["imagick"]=> bool(false)
 ["gmagick"]=> string(8) "2.0.5RC1"
```

Now on how Gmagick is actually used maybe @ottok could share some light since he's already fully set up with that but I couldn't find any way to make core to use it (unless I added an extra WP_Image_Editor as well via apply_filters etc.. which is a totally custom setup and not something that Core by default has).

Please do tell me your ideas and if I'm missing anything else here (or if I got something wrong).

**Comment by ottok** [comment]
We solved this at Seravo by creating a simple wrapper:
```
PRODUCTION [@seravocom:~] $ which convert
/usr/local/bin/convert
PRODUCTION [@seravocom:~] $ cat /usr/local/bin/convert
#!/bin/bash
# Emit a warning, but not to stderr, otherwise the WordPress test runner will fail
# and hosting tests would be needlessly red at https://make.wordpress.org/hosting/test-results/
echo "NOTICE! ImageMagick is not installed, using custom 'convert' wrapper for GraphicsMagick instead."

if [ "$*" == "--version" ]
then
  gm version
else
  gm convert "$@"
fi
```

You could in WP/test-runner just check if the system had ImageMagick or GraphicsMagic and based on that use either `convert` or `gm convert`.

I think that having `convert` in the system namespace is quite a ambiguous name and it is a good thing that GraphicsMagic did not follow suite on this one, but prefixes it's own namespace in the operating system binary name space correctly. So don't ask GraphicsMagic to fix this, but rather you should fix the test runner to support this "better" program naming.

**Comment by mrxkon** [comment]
I'm not asking GM to fix the naming convention obviously haha, my point is that I don't see why we need a shell_exec for this at all (either imagemagick or graphicsmagick), it's not anywhere used in core or in any tests, so why do we need to report the actual Package? Isn't the PHP Module enough?

The wrapper you created is fine @ottok, I saw that from your previous reply, but WP will never use shell_exec for that wrapper to be called either way. Most hosts (afaic at least) don't even have shell_exec enabled as well for security purposes.

That's my question here, having a report for ImageMagick/GraphicsMagick as a Package doesn't make much sense to me, they are not used by PHP they are a system level CLI utility. So why should the test runner report them?

Hence my reasoning of removing the `convert` call completely and just add `gmagick` under php_modules which would again be true/false and simply return the modules version. This way we avoid the error and we also support gmagick at least as a `php_module` which is fine.

**Comment by ottok** [comment]
Yes, removing call to shell 'convert' is the ideal solution.

**Comment by getsource** [comment]
> First of all let's decouple the "Imagick" module vs the actual ImageMagick package ( which includes `convert` also ).
> 
> WordPress has the `WP_Image_Editor_Imagick` & `WP_Image_Editor_GD` as media handling editors. WP_Image_Editor_Imagick is going to be loaded if you simply have `Imagick` module, there's no need to have the actual ImageMagick package.
> 
As far as I'm aware, this is not the case. Per my understanding, Imagick is basically a PHP binding for ImageMagick libraries. This is why it's important to know information about ImageMagick.

If we can collect the same information via Imagick, that's great, though!


> I'm throwing this here as the systems that we're using also don't have `convert` since the actual ImageMagick package isn't installed so I am still getting the `sh: 1: convert: not found` as well since it's missing, but that's minor imho as the module actually exists.

Does core Imagick support work for you without ImageMagick installed? I would be surprised if this is the case.


> Site Health will also check against `Imagick` class or `gd_info()` similarly to showcase what is used on the site.

That's correct! That's a little different than what the runner is doing, since the runner collects the information, displaying it on the site to help everyone troubleshoot test failures.

> With the above being said when I loaded GraphicsMagick & Gmagick respectfully, WP always reverted to using GD instead since there's no mention of Gmagick anywhere in core (as far as I could find).

Correct. While last I checked (some time ago), GraphicsMagick is sometimes used as a replacement for ImageMagick libraries/binaries on the server-side, the Gmagick extension is not supported by core.

> The above information are just added to see if we should "in general" show any information related to Gmagick since it's not used by core itself.

It'd.be great to know though some method if it has a lot of support, from hosts, but agree that it's not something core supports.

> I'm not even sure at this point if we actually need the `convert` and the package being reported at all since only having the `imagick` module is what's actually needed to run `WP_Image_Editor_Imagick`.

When modules are queried via PHP, if the same information can be gathered that way, doing so via PHP rather than through convert would be great. It was my understanding that it did not provide the same info.

It's a recurring issue for WP Imagick support to fail due to mismatched versions of Imagick and ImageMagick, and what formats are supported, or bugs occur are frequently due to the version of ImageMagick that is installed.

> In my opinion to get the best of both worlds here if Gmagick needs to be reported and avoid these errors we can remove the `convert` (no need to read the imagemagick package) and simply add the `gmagick` as a php_module check instead.

I'm mixed on this. The runner doesn't always collect the information via PHP on the test environment -- if it's unable to do that, it comes all from the command line (see `report.php` and `functions.php`), so having some way that it still collects when it can would be good.

I like the idea of it returning "false" or some other way that it matches up with what the reporter expects, if it doesn't exist, though. Is there a reason that won't work here?

**Comment by mrxkon** [comment]
Cool thanks @getsource !

phpinfo returns the ImageMagick version also through the module yeah, I need to check if the numbers are on par with cli and see if we can grab it that way.

> Does core Imagick support work for you without ImageMagick installed?

Let me clarify as what I wrote didn't make much sense there, let's say if you `apt install imagemagick` then you'll most likely end up with `convert` also (guessing via an extra package that is installed in parallel, i need to check it out again), but if you install for example the `imagemagick-6-common` then `convert` doesn't exist even though the library works just fine. Does this make more sense now of why `convert` might not be avail even though Imagick/ImageMagick work as expected?

**Comment by getsource** [comment]
> phpinfo returns the ImageMagick version also through the module yeah, I need to check if the numbers are on par with cli and see if we can grab it that way.

Cool, thanks! Yes, if the same information can be gathered that way -- or has already been gathered that way, I think it makes sense to prefer that method.

> Let me clarify as what I wrote didn't make much sense there, let's say if you `apt install imagemagick` then you'll most likely end up with `convert` also (guessing via an extra package that is installed in parallel, i need to check it out again), but if you install for example the `imagemagick-6-common` then `convert` doesn't exist even though the library works just fine. Does this make more sense now of why `convert` might not be avail even though Imagick/ImageMagick work as expected?

Yes, that makes sense, thanks! I didn't realize that the ImageMagick libraries had a decoupled package available from `convert`. Thanks for the info!

**Comment by mrxkon** [comment]
I've update the PR using the Imagick `getVersion()` as well as added support for gmagick (both module & package) and equivalent functionality. Might be useful to overall gather Gmagick versions (any type) also since hosts might use it even if core doesn't support it by default.

The arrays returned are altered as such:
```
["php_modules"]=>
    ["imagick"]=> string(5) "3.4.4"
    ["gmagick"]=> bool(false)
["system_utils"]=>
    ["imagemagick"]=> string(7) "6.9.7-4"
```
or 
```
["php_modules"]=>
    ["imagick"]=> bool(false)
    ["gmagick"]=> string(8) "2.0.5RC1"
["system_utils"]=>
    ["graphicsmagick"]=> string(3) "1.4"
```

@getsource would this be more helpful? On my end cli/package versions are exactly the same on what PHP reports also for the apis.

@ottok (and anyone else) if you could check this change also it would be great :) to see if it reports fine on other systems, I'm adding/removing packages on the same environment to test at the moment so I might've missed something.

The regex is a bit funny with the "or" but it's just to be able to catch `x.x`, `x.x.x`, `x.x-x` and `x.x.x-x` which I think would suffice for cross-checking.

**Comment by getsource** [comment]
Thanks @mrxkon !  I like the idea of including the information the way you're proposing.

I noticed while testing yesterday that Imagick extension doesn't always return the same information (I had to recompile Imagick to get it to report the newly installed ImageMagick's information), but I'm not sure how much of an edge case that is.
