### ISSUE TITLE
Travis build fails because environment variables not set

### ISSUE THREAD

**Issue by earnjam** [WordPress/phpunit-test-runner#86]
See: https://travis-ci.com/WordPress/phpunit-test-runner/builds/100917327

**Comment by getsource** [comment]
I'm wondering what the best thing to do here is, because my understanding is that https://github.com/WordPress/phpunit-test-runner/blob/master/.travis.yml is an example file for folks setting up the test runner, rather than something to run on Travis for testing or build on *this* Github repo.

I think it'd be great if we had tests, but I as far as I'm aware, there aren't any. Are there any common ways to get have Github stop trying to build when a `.travis.yml` is present?

Wondering if it's possible to stop the failures without renaming the file, in case folks are using it directly from a clone.
