### ISSUE TITLE
phpunit-test-runner user addition please

### ISSUE THREAD

**Issue by redscott** [WordPress/phpunit-test-runner#98]
Hello Guys,
Scott from redIT here I think I've got everything setup and ready to go now can you please add 'redithostingbot' to the test users list please.
The assigned eMail address is 'serveradmin@redit.co.uk'

Thanks guys.
~Scott

**Comment by getsource** [comment]
Hi Scott!

I took a look at the profile, and it doesn't currently make it very clear which host it is for.

Could you please update the profile (Name, Logo/Gravatar, URL) so that visitors to the hosting test results page (https://make.wordpress.org/hosting/test-results/) can tell who is contributing results?

Thanks much!

**Comment by redscott** [comment]
Hi Mike,
Sorry thought that was all done.
Should be good now though I've waited and checked too.

~Scott

**Comment by getsource** [comment]
Thanks so much! It's added, and you should receive an invitation sent to the email address on the account.

Please let me know if you have any questions!
